# 用 panic! 处理不可恢复的错误

- [用 panic! 处理不可恢复的错误](#用-panic-处理不可恢复的错误)
  - [对应 panic 时的栈展开或终止](#对应-panic-时的栈展开或终止)
  - [调用 panic!](#调用-panic)
  - [使用 panic! 的 backtrace](#使用-panic-的-backtrace)

Rust 将错误分为两大类：**可恢复的（recoverable）** 和 **不可恢复的（unrecoverable）** 错误。

Rust 有 `Result<T, E>` 类型，用于处理可恢复的错误，还有 `panic!` 宏，在程序遇到不可恢复的错误时停止执行。

当执行 `panic!` 宏时，程序会打印出一个错误信息，展开并清理栈数据，然后接着退出。

## 对应 panic 时的栈展开或终止

当出现 panic 时，程序默认会开始 **展开（unwinding）**，这意味着 Rust 会回溯栈并清理它遇到的每一个函数的数据，不过这个回溯并清理的过程有很多工作。另一种选择是直接 **终止（abort）**，这会不清理数据就退出程序。那么程序所使用的内存需要由操作系统来清理。

如果需要项目的最终二进制文件越小越好，panic 时通过在 Cargo.toml 的 `[profile]` 部分增加 `panic = 'abort'`，可以由展开切换为终止。例如，如果想要在 release 模式中 panic 时直接终止：

```toml
[profile.release]
panic = 'abort'
```

## 调用 panic!

```rust
fn main() {
    panic!("crash and burn");
}
```

运行程序将会出现类似这样的输出：

```
$ cargo run
   Compiling panic v0.1.0 (/home/endruz/code/endruz/hello-rust/9.1/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.93s
     Running `target/debug/panic`
thread 'main' panicked at 'crash and burn', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

倒数第二行显示了 panic 提供的信息并指明了源码中 panic 出现的位置：`src/main.rs:2:5` 表明这是 src/main.rs 文件的第二行第五个字符。

在其他情况下，`panic!` 可能会出现在我们的代码所调用的代码中。错误信息报告的文件名和行号可能指向别人代码中的 `panic!` 宏调用，而不是我们代码中最终导致 `panic!` 的那一行。我们可以使用 `panic!` 被调用的函数的 backtrace 来寻找代码中出问题的地方。

## 使用 panic! 的 backtrace

```rust
fn main() {
    let v = vec![1, 2, 3];

    v[99];
}
```

运行程序将会出现类似这样的输出：

```
$ cargo run
   Compiling panic v0.1.0 (/home/endruz/code/endruz/hello-rust/9.1/panic)
    Finished dev [unoptimized + debuginfo] target(s) in 0.63s
     Running `target/debug/panic`
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src/main.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

错误指向 main.rs 的第 4 行，这里我们尝试访问索引 99。

下面的说明（note）行提醒我们可以设置 `RUST_BACKTRACE` 环境变量来得到一个 backtrace。backtrace 是一个执行到目前位置所有被调用的函数的列表。Rust 的 backtrace 跟其他语言中的一样：阅读 backtrace 的关键是从头开始读直到发现你编写的文件。这就是问题的发源地。这一行往上是你的代码所调用的代码；往下则是调用你的代码的代码。这些行可能包含核心 Rust 代码，标准库代码或用到的 crate 代码。

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/panic`
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src/main.rs:4:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/slice/index.rs:241:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/vec/mod.rs:2533:9
   6: panic::main
             at ./src/main.rs:4:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
